name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: SEU_PROJECT_ID
  REGION: us-central1
  BACKEND_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/cancermama-backend
  FRONTEND_IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/cancermama-frontend

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Auth in GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Backend Image
        working-directory: ./backend
        run: docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} .

      - name: Push Backend Image
        run: docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cancermama-backend
          image: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            ENVIRONMENT=production
          secrets: |
            GEMINI_API_KEY=GEMINI_API_KEY:latest

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Auth in GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Injeta a URL do backend gerada no passo anterior usando vari√°vel
      - name: Build Frontend Image
        working-directory: ./frontend
        run: docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} .

      - name: Push Frontend Image
        run: docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cancermama-frontend
          image: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: '--allow-unauthenticated'
